# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Project Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, default: "", date_format: "YEAR.MM.DD" }
      - {label: "Categories", name: "categories", widget: "select", options: ["dramaturgy", "choreography", "collective-works"], required: true }
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body tekst", name: "body", widget: "markdown", required: false }
      - {label: "Reviews", name: "reviews", widget: "markdown", required: false }
      - {label: "Credits", name: "credits", widget: "markdown", required: false }
    # PAGES
  - name: "about"
    label: "About"
    folder: "about.md"
    sort: "title:asc"
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Upcoming", name: "upcoming", widget: "markdown", required: false }
      - {label: "Contact", name: "contact", widget: "markdown", required: false }
