backend:
  name: git-gateway
  branch: Patch-1 # Branch to update (optional; defaults to main)

media_folder: "assets/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "Posts"
    label: "Posts"
    description: "All Posts"
    folder: "src/_posts"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "select", options: ["post", "post-video"] }
      - { label: "Kunde", name: "kunde", widget: "string" }
      - { label: "Vimeo Id", name: "vimeo_id", widget: "number" }
      - { label: "Order (mindst først)", name: "order", widget: "number" }
